// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Common.Data.Domain.Models
{
    public partial class EmployeeRole
    {
        public EmployeeRole()
        {
            Employee = new HashSet<Employee>();
        }

        [Key]
        public int RoleId { get; set; }
        [Required]
        [StringLength(20)]
        public string RoleName { get; set; }
        [StringLength(20)]
        public string RoleDisplayName { get; set; }
        public int? SortNo { get; set; }
        [StringLength(20)]
        public string PostAccount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PostDate { get; set; }
        [StringLength(20)]
        public string MdfAccount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? MdfDate { get; set; }

        [InverseProperty("Role")]
        public virtual ICollection<Employee> Employee { get; set; }
    }
}