// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Common.Data.Domain.Models
{
    public partial class FIWContext : DbContext
    {
        public FIWContext()
        {
        }

        public FIWContext(DbContextOptions<FIWContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeRole> EmployeeRole { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Department>(entity =>
            {
                entity.HasKey(e => e.DeptId)
                    .HasName("PK__Departme__014881AEB4867D8C");

                entity.HasIndex(e => e.DeptName)
                    .HasName("UIX_Department")
                    .IsUnique();

                entity.Property(e => e.MdfAccount).IsUnicode(false);

                entity.Property(e => e.PostAccount).IsUnicode(false);
            });

            modelBuilder.Entity<Employee>(entity =>
            {
                entity.HasKey(e => e.EmpId)
                    .HasName("PK__Employee__AF2DBB99F03FC265");

                entity.HasIndex(e => e.EmpAccount)
                    .HasName("UIX_Employee")
                    .IsUnique();

                entity.Property(e => e.Email).IsUnicode(false);

                entity.Property(e => e.EmpAccount).IsUnicode(false);

                entity.Property(e => e.EmpPassword).IsUnicode(false);

                entity.Property(e => e.MdfAccount).IsUnicode(false);

                entity.Property(e => e.PostAccount).IsUnicode(false);

                entity.HasOne(d => d.Dept)
                    .WithMany(p => p.Employee)
                    .HasForeignKey(d => d.DeptId)
                    .HasConstraintName("FK_Employee_Department");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.Employee)
                    .HasForeignKey(d => d.RoleId)
                    .HasConstraintName("FK_Employee_EmployeeRole");
            });

            modelBuilder.Entity<EmployeeRole>(entity =>
            {
                entity.HasKey(e => e.RoleId)
                    .HasName("PK__Employee__8AFACE1A339F528F");

                entity.HasIndex(e => e.RoleName)
                    .HasName("UIX_EmployeeRole")
                    .IsUnique();

                entity.Property(e => e.MdfAccount).IsUnicode(false);

                entity.Property(e => e.PostAccount).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}